name: Test Version Check

on:
  push:
    paths:
      - .github/workflows/version-check.yml
      - .github/workflows/test-version-check.yml
      - tests/version-check/**

jobs:
  run-version-check:
    strategy:
      matrix:
        files:
          - tests/version-check/top-level.json
          - tests/version-check/second-level.json

    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.run.outputs.version }}
      previous-version: ${{ steps.run.outputs.previous-version }}
      changed: ${{ steps.run.outputs.changed }}

    steps:
      - name: Run reusable workflow
        id: run
        uses: ./.github/workflows/version-check.yml
        with:
          file-name: ${{ matrix.files }}

      - name: Log outputs
        run: |
          echo "Version: ${{ steps.run.outputs.version }}"
          echo "Previous Version: ${{ steps.run.outputs.previous-version }}"
          echo "Changed: ${{ steps.run.outputs.changed }}"