name: Test Version Check

on:
  push:
    paths:
      - .github/workflows/version-check.yml
      - .github/workflows/test-version-check.yml
      - tests/version-check/**

jobs:
  run-version-check:
    uses: ./.github/workflows/version-check.yml
    with:
      file-name: tests/version-check/top-level.json
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  log-results:
    needs: run-version-check
    runs-on: ubuntu-latest
    steps:
      - name: Log Outputs
        run: |
          echo "Version: ${{ needs.run-version-check.outputs.version }}"
          echo "Previous Version: ${{ needs.run-version-check.outputs.previous-version }}"
          echo "Changed: ${{ needs.run-version-check.outputs.changed }}"