name: Test Version Check

on:
  push:
    paths:
      - .github/workflows/version-check.yml
      - .github/workflows/test-version-check.yml
      - tests/version-check/**

jobs:
  run-version-check:
    uses: ./.github/workflows/version-check.yml
    strategy:
      matrix:
        include:
          - file: tests/version-check/top-level.json

          - file: tests/version-check/top-level-different-name.json
            path: .v

          - file: tests/version-check/second-level.json
            path: .object.version
    with:
      file-name: ${{ matrix.file }}
      json-version-path: ${{ matrix.path }}
      fail-on-no-change: false
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}