name: Test Version Check

on:
  push:
    paths:
      - .github/workflows/version-check.yml
      - .github/workflows/test-version-check.yml
      - tests/version-check/**

jobs:
  run-version-check:
    uses: ./.github/workflows/version-check.yml
    strategy:
      matrix:
        file:
          - tests/version-check/top-level.json
          - tests/version-check/second-level.json
    with:
      file-name: ${{ matrix.file }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}